version: '3.8'

services:
  # ==================== 数据存储服务 ==================== #
  
  mongodb-prod:
    image: mongo:7.0
    container_name: nutriguide-mongodb-prod
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ADMIN_PASSWORD}
      MONGO_INITDB_DATABASE: nutriguide_prod
    ports:
      - "27019:27017"
    volumes:
      - mongodb_prod_data:/data/db
      - mongodb_prod_config:/data/configdb
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - nutriguide-prod
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

  redis-prod:
    image: redis:7.2-alpine
    container_name: nutriguide-redis-prod
    restart: unless-stopped
    ports:
      - "6381:6379"
    volumes:
      - redis_prod_data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - nutriguide-prod
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    command: redis-server /usr/local/etc/redis/redis.conf

  # ==================== 后端API服务 ==================== #
  
  backend-api-prod:
    build:
      context: ./backend_node
      dockerfile: Dockerfile
      target: production
    container_name: nutriguide-backend-api-prod
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGODB_URI: mongodb://admin:${MONGODB_ADMIN_PASSWORD}@mongodb-prod:27017/nutriguide_prod?authSource=admin
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: 1h
      JWT_REFRESH_EXPIRES_IN: 30d
      REDIS_URL: redis://redis-prod:6379
      LOG_LEVEL: warn
      CORS_ORIGIN: ${CORS_ORIGIN}
      API_RATE_LIMIT: 1000
      FILE_UPLOAD_LIMIT: 50MB
    ports:
      - "3002:3000"
    volumes:
      - backend_uploads_prod:/app/uploads
      - backend_logs_prod:/app/logs
    depends_on:
      mongodb-prod:
        condition: service_healthy
      redis-prod:
        condition: service_healthy
    networks:
      - nutriguide-prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 15s
      retries: 5
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3

  # ==================== 前端Web服务 ==================== #

  frontend-web-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: runner
      args:
        NODE_ENV: production
        VITE_APP_ENV: production
        VITE_API_BASE_URL: ${FRONTEND_API_BASE_URL:-http://localhost:4002}
        VITE_APP_NAME: NutriGuide
        VITE_APP_VERSION: 1.0.0
        VITE_DEBUG: false
    container_name: nutriguide-frontend-web-prod
    restart: unless-stopped
    ports:
      - "4002:80"
    depends_on:
      - backend-api-prod
    networks:
      - nutriguide-prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4002/health"]
      interval: 30s
      timeout: 15s
      retries: 5
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3

# ==================== 网络配置 ==================== #

networks:
  nutriguide-prod:
    driver: bridge
    name: nutriguide-prod-network

# ==================== 数据卷配置 ==================== #

volumes:
  mongodb_prod_data:
    name: nutriguide-mongodb-prod-data
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/lib/nutriguide/mongodb'
  mongodb_prod_config:
    name: nutriguide-mongodb-prod-config
  redis_prod_data:
    name: nutriguide-redis-prod-data
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/lib/nutriguide/redis'
  backend_uploads_prod:
    name: nutriguide-backend-uploads-prod
  backend_logs_prod:
    name: nutriguide-backend-logs-prod 